CREATE TABLE TEST_TABLE (
  ID NUMBER(15) PRIMARY KEY,
  APP_NAME NVARCHAR2(32),
  APP_COL NVARCHAR2(32),
  STATUS NVARCHAR2(20),
  EMAIL NVARCHAR2(64),
  VENDOR NVARCHAR2 (32)
);

create sequence SEQ_TEST_TABLE;