name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean build
  test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'release')
    steps:
      - name: Publish
        run: echo 'Publish version to maven central'
